require("plugins_config.which-key")
require("plugins_config.oil")
require("plugins_config.colorscheme")
require("plugins_config.gitsigns")
require("plugins_config.conform")
require("plugins_config.aerial")
require("plugins_config.vim-test")
require("plugins_config.mini")
require("plugins_config.indent-blanklines")
-- require("plugins_config.bufferline") -- trying to live without bufferline

require("plugins_config.telescope")
require("plugins_config.cmp")
require("plugins_config.lspconfig")
require("plugins_config.treesitter")
